version: "2"

services:
    ### Workspace Utilities Container ###########################
    nodejs:
        image: node:8.9-alpine
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
        environment:
            - NODE_PORT=8080
            - NODE_ENV=development
            - APP_ENV=development
            - URL_PREFIX=/api/v1

            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USERNAME=user
            - DB_PASSWORD=password
            - DB_DATABASE=db

        command: ["/bin/sh", "-c", "yarn && yarn dev"]
    ### PostgresDB Container #######################################
    postgres:
        image: postgres:11
        ports:
            - "35432:5432"
        volumes:
            - ./data/postgres:/data/db
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=db

### Add more Containers below ###############################
# use [ docker network create microservicenetwork ] เพื่อสร้าง mapmagiccloud(your network name้) network ขึ้นมาก่อน
networks:
    default:
        external:
            name: microservicenetwork
